CREATE TABLE IF NOT EXISTS "auth"."users" (
    "id" UUID DEFAULT GEN_RANDOM_UUID() NOT NULL,
    "name" CHARACTER VARYING NOT NULL,
    "surname" CHARACTER VARYING NOT NULL,
    "username" CHARACTER VARYING NOT NULL,
    "email" CHARACTER VARYING NOT NULL,
    "hash" CHARACTER VARYING NOT NULL
);