import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";

import { SidebarProvider } from "@/ui/sidebar";
import { Toaster } from "@/ui/sonner";

import Sidebar from "./components/Sidebar";
import { AuthProvider } from "./contexts/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={geistSans.className}>
      <body>
        <AuthProvider>
          <SidebarProvider>
            <Sidebar />
            <main className="flex-1">{children}</main>
            <Toaster />
          </SidebarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
